### ISSUE TITLE
Add option to only apply a margin when Gitako is open to the header

### ISSUE THREAD

**Issue by SpedNSFW** [EnixCoda/Gitako#113]
Instead of applying the left margin to the entire page when Gitako is open, I'd rather it was applied only to the header. Moving the `with-gitako-spacing` class down to the `.js-header-wrapper` class solves this rather simply.

This should be a toggle-able option that is disabled by default. This feature would mainly be intended for larger monitors that have enough screen real estate that opening a panel on the side doesn't impact anything.

The following styles can also achieve the same effect:

```css
.with-gitako-spacing {
    margin-left: 0;
}

.with-gitako-spcaing .js-header-wrapper {
    margin-left: var(--gitako-width);
}
```

**Comment by EnixCoda** [comment]
Hi @SpedNSFW 

I tried the styles you provided.

![image](https://user-images.githubusercontent.com/7480839/102008068-cf5ffe80-3d68-11eb-8c66-78eff575bb2b.png)

And the navigation bar gets covered under Gitako unexpectedly.

---

If I understood it correctly, it was the shift of page content before/after toggling that bothers you, right?

Gitako had such feature to preserve page content always at the center at about `v0.7.*` version. But it has been deprecated because manipulating styles of GitHub is harder than I expected. Especially at recent time, GitHub is refactoring its page with primer components, which emits classnames that cannot be predicted.

So I chose to make styles of Gitako to be isolated from GitHub's. :)

**Comment by SpedNSFW** [comment]
I think the issue comes down to screen sizes. For larger sizes, moving the entire page content over is very annoying. It's unnecessary and moves the content so it's no longer center.

I have included an image below of what it looks like for me. Note I am using a dark stylesheet that does not change the page layout in anyway.

![image](https://user-images.githubusercontent.com/68614336/102008493-0e03b200-3d85-11eb-8f31-a15a898fbe74.png)

At 1080p with a width of 300px, the gitako panel fits in perfectly. For even larger displays like my 1440p monitor, it just makes sense.

So perhaps changing the stylesheet to something like this would work:

```css
@media (min-width: 1920px) {
    .with-gitako-spacing {
        margin-left: 0;
    }
    .with-gitako-spacing .js-header-wrapper {
        margin-left: var(--gitako-width);
    }
}
```
