### ISSUE TITLE
[Feature] Option to change code font

### ISSUE THREAD

**Issue by NayamAmarshe** [EnixCoda/Gitako#234]
Would be great to have an option to change Github's code font to be something else like Cascadia Code, Fira Code, etc.

**Comment by EnixCoda** [comment]
Hi @NayamAmarshe 

Sorry that this might not be implemented in Gitako. Personally, I love Cascadia Code and Fira Code, too. But Gitako may not attempt to override GitHub's style anymore. I'd suggest you look up alternative extensions or simply add custom CSS with proper extension,

```css
.blob-code-inner {
    font-family: Cascadia Code,Fira Code,ui-monospace,SFMono-Regular,SF Mono,Menlo,Consolas,Liberation Mono,monospace;
}
```
