### ISSUE TITLE
Prefer clear theme!

### ISSUE THREAD

**Issue by PeterDing** [EnixCoda/Gitako#96]
I think that removing the border line would be more nice.

<img width="476" alt="Screen Shot 2020-11-07 at 9 39 36 AM" src="https://user-images.githubusercontent.com/670690/98428805-317c7280-20de-11eb-8399-f4bde95d914e.png">

**Comment by acbetter** [comment]
+1，而且行间距好宽，项目东西多的时候，上下翻起来累。

```css
.gitako-side-bar .gitako-side-bar-body .gitako-side-bar-content .file-explorer .node-item {
    border-bottom: none;
}
```
